// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.composite.grpc.service;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.composite.grpc.service.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
