// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.composite.grpcInterface.service;

public interface UserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.composite.grpcInterface.service.UserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 2;</code>
   */
  String getSex();
  /**
   * <code>string sex = 2;</code>
   */
  com.google.protobuf.ByteString
      getSexBytes();
}
