// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.composite.grpcInterface.base;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.composite.grpcInterface.base.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; requestData = 1;</code>
   */
  int getRequestDataCount();
  /**
   * <code>map&lt;string, string&gt; requestData = 1;</code>
   */
  boolean containsRequestData(
          String key);
  /**
   * Use {@link #getRequestDataMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getRequestData();
  /**
   * <code>map&lt;string, string&gt; requestData = 1;</code>
   */
  java.util.Map<String, String>
  getRequestDataMap();
  /**
   * <code>map&lt;string, string&gt; requestData = 1;</code>
   */

  String getRequestDataOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; requestData = 1;</code>
   */

  String getRequestDataOrThrow(
          String key);
}
