// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.composite.grpcInterface.base;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.composite.grpcInterface.base.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; responseData = 1;</code>
   */
  int getResponseDataCount();
  /**
   * <code>map&lt;string, string&gt; responseData = 1;</code>
   */
  boolean containsResponseData(
          String key);
  /**
   * Use {@link #getResponseDataMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getResponseData();
  /**
   * <code>map&lt;string, string&gt; responseData = 1;</code>
   */
  java.util.Map<String, String>
  getResponseDataMap();
  /**
   * <code>map&lt;string, string&gt; responseData = 1;</code>
   */

  String getResponseDataOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; responseData = 1;</code>
   */

  String getResponseDataOrThrow(
          String key);
}
