// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.composite.grpcInterface.base;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_composite_grpcInterface_base_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_composite_grpcInterface_base_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_composite_grpcInterface_base_Response_ResponseDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_composite_grpcInterface_base_Response_ResponseDataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016response.proto\022 com.composite.grpcInte" +
      "rface.base\"\223\001\n\010Response\022R\n\014responseData\030" +
      "\001 \003(\0132<.com.composite.grpcInterface.base" +
      ".Response.ResponseDataEntry\0323\n\021ResponseD" +
      "ataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001" +
      "B\021B\rResponseProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_composite_grpcInterface_base_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_composite_grpcInterface_base_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_composite_grpcInterface_base_Response_descriptor,
        new String[] { "ResponseData", });
    internal_static_com_composite_grpcInterface_base_Response_ResponseDataEntry_descriptor =
      internal_static_com_composite_grpcInterface_base_Response_descriptor.getNestedTypes().get(0);
    internal_static_com_composite_grpcInterface_base_Response_ResponseDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_composite_grpcInterface_base_Response_ResponseDataEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
