// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.composite.grpcInterface.base;

public final class ResultProto {
  private ResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_composite_grpcInterface_base_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_composite_grpcInterface_base_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_composite_grpcInterface_base_Request_RequestDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_composite_grpcInterface_base_Request_RequestDataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rrequest.proto\022 com.composite.grpcInter" +
      "face.base\"\216\001\n\007Request\022O\n\013requestData\030\001 \003" +
      "(\0132:.com.composite.grpcInterface.base.Re" +
      "quest.RequestDataEntry\0322\n\020RequestDataEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\017B\013Re" +
      "sultProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_composite_grpcInterface_base_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_composite_grpcInterface_base_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_composite_grpcInterface_base_Request_descriptor,
        new String[] { "RequestData", });
    internal_static_com_composite_grpcInterface_base_Request_RequestDataEntry_descriptor =
      internal_static_com_composite_grpcInterface_base_Request_descriptor.getNestedTypes().get(0);
    internal_static_com_composite_grpcInterface_base_Request_RequestDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_composite_grpcInterface_base_Request_RequestDataEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
