server:
  port: 8071
spring:
  application:
    name: grpc-client
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: false
grpc:
  client:
    grpc-server:
      #address: static://127.0.0.1:9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext